version: "3"
volumes:
  db:
services:
  nextcloud:
    image: nextcloud
    volumes:
      - ./videos:/var/www/html/data
    ports:
      - 8081:80
    depends_on:
      - db
    links:
      - db
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=12345
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
  embyserver:
    image: emby/embyserver
    ports:
      - 8082:8096
    volumes:
      - ./progamData:/config
      - ./videos:/mnt/share
    environment:
      - UID=0
      - GID=0
      - GIDLIST=39


